name: Alpine CI
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    paths:
      - "alpine/**"
env:
  APP: alpine
  REGISTRY: ghcr.io/elmariovi
jobs:
  build:
    name: Build Alpine
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./${{ env.APP }}/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.APP }}:latest
        env:
          DOCKER_BUILD_SUMMARY: false
      - name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ${{ env.REGISTRY }}/${{ env.APP }}:latest
          annotations: true
          dockerfile: ./${{ env.APP }}/Dockerfile
      - name: Clean up untagged images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.APP }}
          package-type: container
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}
