name: Proton CI
on:
  workflow_dispatch:
  push:
    paths:
      - "proton/**"
env:
  APP: proton
  REGISTRY: ghcr.io/elmariovi
  PROTON_VERSION: "10-30"
jobs:
  build:
    name: Build Proton
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./${{ env.APP }}/
          push: true
          build-args: |
            PROTON_VERSION=${{ env.PROTON_VERSION }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.APP }}:${{ env.PROTON_VERSION }}
        env:
          DOCKER_BUILD_SUMMARY: false
      - name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ${{ env.REGISTRY }}/${{ env.APP }}:${{ env.PROTON_VERSION }}
          annotations: true
          dockerfile: ./${{ env.APP }}/Dockerfile
      - name: Clean up untagged images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.APP }}
          package-type: container
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}
